### ISSUE TITLE
Any plans for a release?

### ISSUE THREAD

**Issue by idgserpro** [collective/collective.xsendfile#10]
We're testing this plugin in some websites and it's working flawlessly. Unfortunately, we're using it from source instead of downloading from pypi.

Do you have any date on mind for creating the 1.1 release on pypi? Thanks!

**Comment by gforcada** [comment]
Already asked on #5 

Fixing travis and doing the release yourself (seems to not have been registered on pypi so far) would be enough to get a release out.
